# Yarn 4 Configuration

# Use node_modules linker for maximum compatibility with Next.js and Cloudflare Workers
nodeLinker: node-modules

# Package manager version
yarnPath: .yarn/releases/yarn-4.12.0.cjs

# Enable global cache
enableGlobalCache: true

# Network settings
httpTimeout: 60000
networkConcurrency: 8

# Install settings
nmHoistingLimits: workspaces

# Disable telemetry
enableTelemetry: false
